<a href="https://colab.research.google.com/github/pratik6217/Python-Notebooks/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question - 1


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
arr = np.arange(2,50,3).reshape(16)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question - 2

In [18]:
l1 = list(map(int, input().split()))
l2 = list(map(int, input().split()))
arr1 = np.array(l1)
arr2 = np.array(l2)

arr = np.concatenate([arr1, arr2])
print(arr)
print(np.sort(arr1))
print(np.sort(arr2))

1 2 3 4 5
6 7 8 9 10
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]


Question - 3

In [24]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
shape = arr.shape
dimension = arr.ndim
size = arr.size
print(shape)
print(dimension)
print(size)

(2, 5)
2
10


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("dimensiom:",arr.ndim)
new_arr = arr.reshape(2,5)
print(new_arr)
print("dimension:",new_arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
dimensiom: 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
dimension: 2


Question - 5

In [32]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Stacked Vertically:")
v = np.concatenate((arr1,arr2),axis=0)
print(v)
print("Stacked Horizontally:")
h = np.concatenate((arr1,arr2),axis=1)
print(h)

Stacked Vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Stacked Horizontally:
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


Question - 6

In [52]:
arr = np.array([1,2,3,4,5,6,1,3,5,6,7,8,9,10])
print("Old Array:",arr)

np.unique(arr,return_counts=True)



Old Array: [ 1  2  3  4  5  6  1  3  5  6  7  8  9 10]


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([2, 1, 2, 1, 2, 2, 1, 1, 1, 1]))